### ISSUE TITLE
Summary 

### ISSUE THREAD

**Issue by gdedi001** [AlbertoProgra/prj-rev-bwfs-dasmoto#1]
Fantastic job on your project - your HTML is very well organized and you used semantic tags, like `<h1>` and `<h2>` purposefully. In addition to this, utilizing the `<span>` tag was a great way to make your text stand out. 

Some areas for improvement here are with your usage of the `class` attribute and how your CSS code is organized. Since the classes aren't repeating, I highly recommend using the `id` attribute. I also recommend incorporating Google's best practice _Declaration Order_ to your CSS.

I recommend reading these two articles and implementing the content into your project.
[id vs. class](https://css-tricks.com/the-difference-between-id-and-class/)
[Declaration Order](https://google.github.io/styleguide/htmlcssguide.html#Declaration_Order)

**Comment by AlbertoProgra** [comment]
Once again thank you so much for the support and the feeding, i'm on to that "Reading and fixing my errors"
