### ISSUE TITLE
Replace with id attribute

### ISSUE THREAD

**Issue by gdedi001** [AlbertoProgra/prj-rev-bwfs-dasmoto#2]
Classes should only be used when two or more instances exist.

https://github.com/AlbertoProgra/prj-rev-bwfs-dasmoto/blob/master/DasmotosArts/index.html#L10
https://github.com/AlbertoProgra/prj-rev-bwfs-dasmoto/blob/master/DasmotosArts/index.html#L16
https://github.com/AlbertoProgra/prj-rev-bwfs-dasmoto/blob/master/DasmotosArts/index.html#L22

**Comment by AlbertoProgra** [comment]
Thank you i already fixed them!
