### ISSUE TITLE
Built in colors

### ISSUE THREAD

**Issue by gdedi001** [AlbertoProgra/prj-rev-bwfs-dasmoto#3]
Great job using the built in colors. As a developer its always great to know what built in features are available!
https://github.com/AlbertoProgra/prj-rev-bwfs-dasmoto/blob/master/DasmotosArts/resources/css/style.css#L25-L33

**Comment by AlbertoProgra** [comment]
@gdedi001 just a question how do you know as a developer, what built in colors are available to use? i mean that the colors i used were those that the project suggested for the layout.

**Comment by gdedi001** [comment]
Here's a list! https://www.w3schools.com/cssref/css_colors.asp
